language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer install --prefer-source --no-interaction
  - composer require phpunit/phpunit 5.7.3

script: vendor/bin/phpunit --debug

after_success:
  - travis_retry php vendor/bin/coveralls
